### ISSUE TITLE
color method should return current color

### ISSUE THREAD

**Issue by nasser** [nasser/zajal#48]
``` ruby
color 128, 64, 32
color # => [128, 64, 32, 255]

color 32
color # => [32, 32, 32, 255]

color :blue
color # => [0, 0, 255, 255]
```

when color classes are done, this should return a color class instance

**Comment by judy-zz** [comment]
Do you still want to return an array of RGBA values? Or with the new color classes, could we instead return the exact instance of the color being used, like a Color::Hsv object?

**Comment by nasser** [comment]
6460d19d80 builds on your implementation to return the actual color object. I'm happy with that for now.
